const FB_EXPR = {
    DOT_PHP_START: /^.+\.php/,
    DOT_PHP_END: /.+\.php$/,
};

const FB_PATH = {
    DIRECTORY: '/directory',
    DIRECTORY_PAGES: '/directory/pages',
    META: '/meta',
    HELP: '/help',
    BUSINESS: '/business',
    SUPPORT: '/support',
    CREATORS: '/creators',
    AR_STUDIO: '/ar-studio',
    FB_GAMING_HOME: '/fbgaminghome',
    PRODUCTS: '/products',
    DOCS: '/docs',
    BLOG: '/blog',
    DEVELOPER_CIRCLES: '/developercircles',
    TECHNOLOGIES: '/technologies',
    ACTIONS: '/action',
    GPA: '/gpa',
    FACEBOOK_MEDIA: '/facebookmedia',
    JOURNALISM_PROJECT: '/journalismproject',
    AUDIENCE_NETWORK: '/audiencenetwork',
    SAFETY: '/safety',
    SUPPORT_SMALL_BUSINESS: '/supportsmallbusiness',
    SOCIAL_IMPACT: '/social-impact',
    COMMUNITY_STANDARS: '/communitystandards',
    AD_PREFERENCES: '/adpreferences',
    FACEBOOK_PAY: '/facebook_pay',
    PEOPLE: '/people',
    POLICY: '/policy',
    TERMS: '/terms',
    JOBS: '/jobs',
    JOBS_JOB_OPENING: '/jobs/job-opening',
    FRIENDS: '/friends',
    SERVICES: '/services',
    PAGES: '/pages',
    PG: '/pg',
    BIZ: '/biz',
    EVENTS: '/events',
    WATCH: '/watch',
    GROUPS: '/groups',
    POSTS: '/posts',
    STORIES: '/stories',
    PLACES: '/places',
    PUBLIC: '/public',
    COMMUNITY: '/copmmunity',
    MARKETPLACE: '/marketplace',
    VIDEOS: '/videos',
    PHOTO: '/photo',
    NOTES: '/notes',
    PHOTOS: '/photos',
    HASHTAG: '/hashtag',
    PAGES_CATEGORY: '/pages/category',
    PAGE__POSTS: '/posts',
    PAGE__GROUPS: '/groups',
    PAGE__JOBS: '/jobs',
    PAGE__EVENTS: '/events',
    PAGE__REVIEWS: '/reviews',
    PAGE__PHOTOS: '/photos',
    PAGE__ABOUT: '/about',
    PAGE__COMMUNITY: '/community',
    PAGE__GUIDES: '/guides',
    PAGE__OFFERS: '/offers',
    PAGE__FUNDRAISER: '/fundraiser',
    PAGE__SERVICES: '/services',
    PAGE__SHOP: '/shop',
    PAGE__LIVE: '/live',
    PAGE__SETTINGS: '/settings',
};

module.exports = { FB_EXPR, FB_PATH };

// const FB_SUB_PATHS = [
//     FB_PATH.PAGE__POSTS,
//     FB_PATH.PAGE__GROUPS,
//     FB_PATH.PAGE__JOBS,
//     FB_PATH.PAGE__EVENTS,
//     FB_PATH.PAGE__REVIEWS,
//     FB_PATH.PAGE__PHOTOS,
//     FB_PATH.PAGE__ABOUT,
//     FB_PATH.PAGE__COMMUNITY,
//     FB_PATH.PAGE__GfbidES,
//     FB_PATH.PAGE__OFFERS,
//     FB_PATH.PAGE__FUNDRAISER,
//     FB_PATH.PAGE__SERVICES,
//     FB_PATH.PAGE__SHOP,
//     FB_PATH.PAGE__LIVE,
//     FB_PATH.PAGE__SETTINGS,
// ];
